name: Automerge RNAs after 7 days

on:
  schedule:
    - cron: 0 8 * * *

  pull_request_target:
    types:
      - opened
      - synchronized
      - reopened
      - edited
      - labeled
      - unlabeled
      - ready_for_review

  workflow_dispatch:
    inputs:
      pull-request:
        description: Pull Request Number
        required: false

permissions:
  issues: write
  pull-requests: write

jobs:
  applytag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v4.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-pr-message: 'The pull request has been labelled as ready for automerge, as it has been open for 7 days without objection.'
        days-before-stale: 1
        # TODO: change to 7 in prod
        days-before-issue-stale: -1
        # we don't want this to run on issues, only PRs
        days-before-close: -1
        # we don't want anything closed
        stale-pr-label: 'automerge'
        any-of-labels: 'rna'
        # TODO: Check labels with @atg-abhishek
        exempt-pr-labels: 'question,wontfix,invalid,duplicate,objection'
        remove-stale-when-updated: false
        ignore-updates: true

  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: reitermarkus/automerge@v1.5.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: rebase
          do-not-merge-labels: question,wontfix,invalid,duplicate
          required-labels: automerge
          pull-request: ${{ github.event.inputs.pull-request }}
